spring:
  redis:
    database: 0
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
        max-active: 8
        min-idle: 0
    timeout: 10000
    cluster:
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
